### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by phate1** [alxbl/x64dbg-ghidra#1]
Hey great script thanks for taking the time to share

something I noticed today if you don't have for example any bookmarks the script will hit a KeyError would be great to have a bit of handling for that.

also, one other observation was when exporting the database from x64dbg it seems to come out uncompressed so just needed renaming.

thanks

**Comment by alxbl** [comment]
Nice catch on the bookmarks. I'll fix that.

For the x64dbg database, I wasn't aware of an export option, that makes it a lot easier. I will update the documentation to reflect that. There's also an option to save databases uncompressed IIRC, which makes it easier to import in Ghidra.
